apiVersion: v1
kind: Service
metadata:
  name: tmmb-svc
  namespace: demo
  labels:
    app: tmmb-svc
spec:
  selector:
    app: tmmb
  ports:
  - name: 
    port: 8029
    protocol: TCP
  type: LoadBalancer
