apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ida
  namespace: stage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ida
    spec:
      containers:
      - name: ida
        image: ae7bf2c134d5f11e7a174123ab8f20a4-1306207793.us-east-1.elb.amazonaws.com:5494/ida:sprint-16Stage5
        ports:
        - containerPort: 8027
