#!/bin/bash
#
# This hook is for commit message validation.
# To use it, copy this file to your .git/hooks directory and remove the .hook extension
# Use the following command from repo root
# Copy-Item -Path .\commit-msg.hook -Destination .\.git\hooks\commit-msg -Force

tfsRegex="^CB(MR)?-[0-9]+: .*"
msgContents=`cat $1`

if [[ ! $msgContents =~ $tfsRegex ]] ; then
    echo "MISSING JIRA ID IN MESSAGE"
    echo "COMMIT MESSAGE MUST BEGIN WITH JIRA ID AND COLON, SEE BELOW"
    echo "CB-12345: Some commit message"
    exit 1
fi

echo "COMMIT MESSAGE CHECK PASSED"
exit 0