apiVersion: v1
kind: Service
metadata:
  name: dlm-svc
  namespace: stage
  labels:
    app: dlm-svc
spec:
  selector:
    app: dlm
  ports:
  - name: 
    port: 8003
    protocol: TCP
  type: ClusterIP
