apiVersion: v1
kind: Service
metadata:
  name: dadb-svc
  namespace: demo
  labels:
    app: dadb-svc
spec:
  selector:
    app: dadb
  ports:
  - name: tcp
    port: 8026
    protocol: TCP
  type: LoadBalancer
