apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dadb
  namespace: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dadb
    spec:
      containers:
      - name: dadb
        image: ae7bf2c134d5f11e7a174123ab8f20a4-1306207793.us-east-1.elb.amazonaws.com:5494/dadb:sprint-16Demo
        ports:
        - containerPort: 8026
